### PR TITLE
REDUX

### PR DESCRIPTION
**Pull request by Ayush7614**

### CODE REVIEW

**Comment by Surajbokde** [comment]
@Ayush7614 did u add github folder??

**Comment by Ayush7614** [comment]
bro if you have no problem then add it i have no problem if you have add it thats good if you have not add it no problem i am happy i make such more roadmap on this

**Comment by Surajbokde** [comment]
@Ayush7614 already there is git-github folder . just add your resources there and delete your github folder

**Comment by Ayush7614** [comment]
Okk i delete it plss merge my redux roadmap

**Comment by Ayush7614** [comment]
I have delete the github folder now i have added my resources in git and github folder after sometime

**Review by Surajbokde — APPROVED** [review]

**Review by Surajbokde — APPROVED** [review]

**Pull request merged**
